### ISSUE TITLE
how to calculate LSB in code

### ISSUE THREAD

**Issue by zxj329** [cornell-zhang/FracBNN#2]
张老师，您好，我最近阅读了您的FracBNN的论文，首先感谢您的开源，我也已在cifar-10上复现了精度。但我这里还有两个问题不太明白，向您请教下。
1：您在论文中是将一个2bit的数目分成了高1bit的数，以及低1bit的数，然后分别和1bit的权重进行XNOR，得到激活值，但是程序中貌似您计算MSB是用反量化后的2bit的输入进行了sign函数变成了-1和1，然后与1bit的权重进行卷积，最后结果乘以2/3得到MSB，而得到LSB则是反量化的2bit的输入与1bit的权重直接卷积减去MSB的值，我想问您下论文中的XNOR和代码中的卷积是如何对应的（我已阅读了PG这篇论文）。
2：如何在程序中实现将2-bit input直接split成高1bit的数和低1bit的数目，从而使得计算LSB和MSB都可以变成1bit的输入和1bit的权重相乘。
期待您的答复

**Comment by ychzhang** [comment]
Hi @zxj329 ,

Thanks for checking out both our paper and code. If I understand your question correctly, they can essentially be combined into one --- how do we simulate the bit splitting convolution in pytorch (or how is the PG layer implemented). Here is my brief answer:

We are dealing with 2-bit inputs. On hardware we use unsigned integer representations for the 4 possible inputs A_hw {00, 01, 10, 11}. In pytorch, instead, we use A_sw {-1, -1/3, 1/3, 1} accordingly. Training becomes infeasible otherwise. Same for weights, in hardware we use W_hw {0, 1}, but in pytorch we use W_sw {-1, 1}. This discrepancy leads to a scaling factor before the MSB conv and the LSB conv. We find that there's such a relation:

CONVmsb(A, W) = 2/3 * CONV(sign(A_sw), W_sw)

And CONV(sign(A_sw), W_sw) corresponds well to the msb conv on hardware --- CONV(A_hw_msb, W_hw). There is a hidden math that I wouldn't expand here, but it would be straight forward if you work on an example. Or you can checkout the accelerator code and see how we implement the msb conv on FPGA. Thanks again for checking out the repo.

- Yichi
